### ISSUE TITLE
Top-played isn't working

### ISSUE THREAD

**Issue by abhiklodh** [andyruwruw/andyruwruw#2]
I tried to implement your code on my own but I came across an error while trying to access the top-played api. The now playing works perfectly.

This is the error that I see when I go to logs in Vercel

`18:14:55:85
2020-09-14T12:44:56.559Z	acfb5386-6359-4ffb-aa48-dbc59adc39c2	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read property 'map' of undefined","reason":{"errorType":"TypeError","errorMessage":"Cannot read property 'map' of undefined","stack":["TypeError: Cannot read property 'map' of undefined","    at /vercel/54876353/api/top-played.ts:24:34","    at Array.map (<anonymous>)","    at default_1 (/vercel/54876353/api/top-played.ts:23:61)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at Server.<anonymous> (/var/task/___now_helpers.js:813:13)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'map' of undefined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at process.emit (/var/task/__sourcemap_support.js:587:21)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred`

Any help will be appreciated.
Thanks.

**Comment by abhiklodh** [comment]
Maybe it has something to do with the authorisation scope so I'll try to check that out but please let me know if you have any solutions.

**Comment by abhiklodh** [comment]
Okay
I figured it out. It was because of the scope causing issues because I didn't specify all the scopes that your application needed. Thanks anyways. This is an amazing project.
Take care.
