### ISSUE TITLE
Null converted to object in now playing

### ISSUE THREAD

**Issue by guilyx** [andyruwruw/andyruwruw#6]
Hey there,

Set things up on my profile, thanks for the project it's really noice. Ran into issues though:

```
[GET] /now-playing
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at default_1 (/vercel/path3/api/now-playing.ts:54:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Server.<anonymous> (/var/task/___vc_helpers.js:813:13)
```

JS/Web isn't my cup of tea, but tried a few things and figured I'd change this:

```js
let audioFeatures: IAudioFeaturesResponse | object = null;
if (Object.keys(item).length) {
  audioFeatures = await trackAudioFeatures(item.id, Authorization);
}
```

to this

```js
let audioFeatures: IAudioFeaturesResponse | object = null;
if(item) {
  if (Object.keys(item).length) {
    audioFeatures = await trackAudioFeatures(item.id, Authorization);
  }
} else {
  return res.status(500).end();
}
```

worked for me, not sure if it's clean or not. I'll shoot a PR if you're okay with it.

**Comment by guilyx** [comment]
item is actually empty when nothing is currently playing, so I guess it's the "last jammed to" part that doesn't work out for me
